const ICON_MAP: Array<{ keys: string[]; icon: string }> = [
  { keys: ['milch', 'milk'], icon: '🥛' },
  { keys: ['joghurt', 'yogurt', 'yoghurt'], icon: '🫙' },
  { keys: ['käse', 'cheese'], icon: '🧀' },
  { keys: ['butter'], icon: '🧈' },
  { keys: ['sahne', 'schlagobers', 'obers', 'cream'], icon: '🥛' },
  { keys: ['semmel', 'weckerl', 'brötchen', 'gebäck'], icon: '🥐' },
  { keys: ['brot', 'bread', 'toast', 'weißbrot'], icon: '🍞' },
  { keys: ['croissant'], icon: '🥐' },
  { keys: ['ei', 'eier', 'egg'], icon: '🥚' },
  { keys: ['apfel', 'äpfel', 'apple'], icon: '🍎' },
  { keys: ['banane', 'bananen', 'banana'], icon: '🍌' },
  { keys: ['erdbeere', 'strawberry'], icon: '🍓' },
  { keys: ['beere', 'beeren', 'berry', 'berries'], icon: '🫐' },
  { keys: ['orange', 'mandarine', 'clementine'], icon: '🍊' },
  { keys: ['zitrone', 'lemon', 'limette', 'lime'], icon: '🍋' },
  { keys: ['traube', 'trauben', 'grape'], icon: '🍇' },
  { keys: ['kirsche', 'cherry', 'kirschen'], icon: '🍒' },
  { keys: ['melone', 'melon', 'wassermelone'], icon: '🍉' },
  { keys: ['pfirsich', 'peach'], icon: '🍑' },
  { keys: ['birne', 'pear'], icon: '🍐' },
  { keys: ['ananas', 'pineapple'], icon: '🍍' },
  { keys: ['mango'], icon: '🥭' },
  { keys: ['avocado'], icon: '🥑' },
  { keys: ['paradeiser', 'tomate', 'tomato'], icon: '🍅' },
  { keys: ['gurke', 'cucumber'], icon: '🥒' },
  { keys: ['salat', 'lettuce', 'kopfsalat', 'rucola'], icon: '🥬' },
  { keys: ['erdäpfel', 'kartoffel', 'potato'], icon: '🥔' },
  { keys: ['zwiebel', 'onion'], icon: '🧅' },
  { keys: ['knoblauch', 'garlic'], icon: '🧄' },
  { keys: ['karotte', 'möhre', 'karotten', 'carrot'], icon: '🥕' },
  { keys: ['brokkoli', 'broccoli'], icon: '🥦' },
  { keys: ['paprika', 'peperoni', 'bell pepper'], icon: '🫑' },
  { keys: ['mais', 'corn'], icon: '🌽' },
  { keys: ['pilz', 'champignon', 'egerling', 'mushroom'], icon: '🍄' },
  { keys: ['spinat', 'spinach', 'feldsalat'], icon: '🥬' },
  { keys: ['kürbis', 'pumpkin'], icon: '🎃' },
  { keys: ['hühnerfleisch', 'hähnchen', 'huhn', 'hendl', 'chicken'], icon: '🍗' },
  { keys: ['fleisch', 'rindfleisch', 'steak', 'beef', 'rind'], icon: '🥩' },
  { keys: ['schinken', 'speck', 'bacon', 'ham'], icon: '🥓' },
  { keys: ['wurst', 'würstel', 'bratwurst', 'sausage', 'salami'], icon: '🌭' },
  { keys: ['burger', 'hamburger'], icon: '🍔' },
  { keys: ['fisch', 'lachs', 'forelle', 'fish', 'salmon'], icon: '🐟' },
  { keys: ['thunfisch', 'tuna'], icon: '🐟' },
  { keys: ['garnele', 'shrimp', 'meeresfrüchte', 'seafood'], icon: '🦐' },
  { keys: ['reis', 'rice'], icon: '🍚' },
  { keys: ['nudel', 'nudeln', 'pasta', 'spaghetti', 'penne'], icon: '🍝' },
  { keys: ['mehl', 'flour'], icon: '🌾' },
  { keys: ['müsli', 'cornflakes', 'flocken', 'cereal'], icon: '🥣' },
  { keys: ['wasser', 'water', 'mineralwasser'], icon: '💧' },
  { keys: ['saft', 'juice', 'nektar'], icon: '🧃' },
  { keys: ['kaffee', 'coffee', 'espresso', 'kapsel'], icon: '☕' },
  { keys: ['tee', 'tea', 'kräutertee'], icon: '🫖' },
  { keys: ['bier', 'beer', 'radler'], icon: '🍺' },
  { keys: ['wein', 'wine', 'sekt', 'prosecco'], icon: '🍷' },
  { keys: ['soda', 'cola', 'limonade', 'fanta', 'sprite', 'softdrink'], icon: '🥤' },
  { keys: ['schokolade', 'schoko', 'chocolate', 'praline'], icon: '🍫' },
  { keys: ['chips', 'crisps'], icon: '🍟' },
  { keys: ['keks', 'kekse', 'cookies', 'biskuit', 'gebäck'], icon: '🍪' },
  { keys: ['eis', 'speiseeis', 'ice cream', 'glace'], icon: '🍦' },
  { keys: ['zucker', 'sugar', 'staubzucker'], icon: '🍬' },
  { keys: ['honig', 'honey'], icon: '🍯' },
  { keys: ['marmelade', 'jam', 'konfitüre'], icon: '🫙' },
  { keys: ['salz', 'salt', 'meersalz'], icon: '🧂' },
  { keys: ['olivenöl', 'öl', 'oil', 'rapsöl', 'sonnenblumenöl'], icon: '🫒' },
  { keys: ['essig', 'vinegar', 'balsamico'], icon: '🍶' },
  { keys: ['seife', 'soap', 'handseife'], icon: '🧼' },
  { keys: ['zahnpasta', 'zahncreme', 'toothpaste', 'zahnbürste'], icon: '🪥' },
  { keys: ['shampoo', 'duschgel', 'deo', 'deodorant'], icon: '🧴' },
  { keys: ['toilettenpapier', 'klopapier', 'tissue', 'taschentuch'], icon: '🧻' },
  { keys: ['waschmittel', 'weichspüler', 'spülmittel', 'detergent'], icon: '🧺' },
  { keys: ['pizza'], icon: '🍕' },
  { keys: ['suppe', 'soup', 'brühe'], icon: '🍲' },
  { keys: ['krautsalat', 'coleslaw', 'sauerkraut'], icon: '🥗' },
  { keys: ['ei', 'eier', 'egg'], icon: '🥚' },
  { keys: ['tofu', 'soja', 'soy'], icon: '🫘' },
  { keys: ['hülsenfrüchte', 'linsen', 'bohnen', 'lentils', 'beans'], icon: '🫘' },
  { keys: ['nuss', 'nüsse', 'mandel', 'nut', 'nuts'], icon: '🥜' },
  { keys: ['quinoa', 'bulgur', 'couscous'], icon: '🌾' },
];

export function getItemIcon(name: string): string {
  const lower = name.toLowerCase();
  for (const { keys, icon } of ICON_MAP) {
    if (keys.some(k => {
      const idx = lower.indexOf(k);
      if (idx === -1) return false;
      const before = idx === 0 || /\W/.test(lower[idx - 1]);
      const after = idx + k.length === lower.length || /\W/.test(lower[idx + k.length]);
      return before && after;
    })) return icon;
  }
  return '🛒';
}
